### ISSUE TITLE
How to use the trn_pv.part*.rar in the Tmall directory?

### ISSUE THREAD

**Issue by Scofield666** [anonymous0618/MB-GMN#1]
About the tmall data, I wonder how to use the data trn_pv.part*.rar. Does it need us to unzip the rar files and then just use one file as the input or the combination of all the files? 
I would appreciate very much if you help me with the question.

**Comment by Scofield666** [comment]
And by the way, What's the trn_int file mean?

**Comment by akaxlh** [comment]
You can unzip the first rar part file. It's due to Github's restriction on the size of single files.
