### ISSUE TITLE
Taobao数据集的压缩文件是什么？打不开

### ISSUE THREAD

**Issue by Sunscreen123** [anonymous0618/MB-GMN#3]
大佬好，已经正常运行了Beibei数据集，并且推荐指标很好。在淘宝数据集这里有点问题，不知道这几个压缩包是什么，不能解压。2-6都不能解压
![image](https://user-images.githubusercontent.com/39050681/183327656-03483c15-0001-4d32-b26e-ecaf7ad51b10.png)

**Comment by akaxlh** [comment]
你好，感谢对我们工作的关注。这个是用winrar分卷压缩的，为了绕过github的单个文件大小限制。一般用解压工具打开part01就会解压所有的。你可以试一下能不能解压缩，如果实在不行也可以发邮件给我（aka_xia@foxmail.com），通过邮件或者网盘分享给你，但是下载速度也不一定很快。

**Comment by Sunscreen123** [comment]
感谢老师来信，老师的意思是只解压第一个part01得到四个文件就可以用吗？


确实已经完全复现了论文中的结果，感谢开源。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akaxlh/MB-GMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akaxlh/MB-GMN] Taobao数据集的压缩文件是什么？打不开 (Issue #3)





 
***@***.***），通过邮件或者网盘分享给你，但是下载速度也不一定很快。

**Comment by akaxlh** [comment]
解压后加上未压缩的一共5个文件：trn_pv, trn_cart, trn_fav, trn_buy, tst_int。如果你可以正常训练、测试，那就没有问题

**Comment by Sunscreen123** [comment]
没有这个文件，老师可以邮箱发一下吗（全部数据）？麻烦了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akaxlh/MB-GMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月10日(星期三) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akaxlh/MB-GMN] Taobao数据集的压缩文件是什么？打不开 (Issue #3)





 
解压后加上未压缩的一共5个文件：trn_pv, trn_cart, trn_fav, trn_buy, tst_int。如果你可以正常训练、测试，那就没有问题

**Comment by akaxlh** [comment]
好的，你可以给我发一封邮件，我邮件发给你。aka_xia@foxmail.com
